#开发环境

#指定开发环境端口号
server:
  port: 8080

spring:


#    数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: mysql
    password: 15827318595
#    JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    com.lyj.blog: debug
  file: log/blog-dev.log




